collections:
  - name: ansible.windows
    version: ">=1.15.0"
  - name: community.general
    version: ">=7.7.0"
  - name: community.windows
    version: ">=2.2.0"
  - name: ansible.posix
    version: ">=1.4.0"